server:
  port: 3000

spring:
  application:
    name: ecommerce-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.igmghtxipelbsqnenqja.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: n&G-XGvzLm2@&FF

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none   # change to 'none' if tables already exist
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect